import type { Language } from "@/lib/i18n";
import type { WaitlistExperience, WaitlistSchedule, WineLevel } from "@/lib/waitlist";

const es = {
  eyebrow: "Lista de espera & registro prioritario",
  titleMain: "¿Te quedaste",
  titleHighlight: "fuera?",
  subtitle:
    "Nuestras ediciones tienen cupos limitados y suelen agotarse rápido. Al registrarte tendrás acceso anticipado a las reservas, invitaciones exclusivas y beneficios especiales para nuestras próximas catas y encuentros gastronómicos.",
  formEyebrow: "Sin compromiso",
  formTitle: "Regístrate en la lista prioritaria",
  formSubtitle: "Solo toma un minuto. Te escribimos por WhatsApp apenas se libere un cupo o abramos una nueva fecha.",
  sectionContact: "Datos de contacto",
  sectionPreferences: "Preferencias y hábitos de consumo",
  fullName: "Nombre y apellido",
  phone: "WhatsApp",
  phoneHint: "Con código de área, p. ej. 0414-000-0000.",
  email: "Correo electrónico",
  selectPlaceholder: "Selecciona una opción",
  spots: "¿Cuántas personas?",
  spotsOption: (n: number) => (n === 1 ? "1 persona" : `${n} personas`),
  experiences: "¿Qué tipo de experiencias o catas te gustaría vivir con nosotros?",
  experiencesHint: "Puedes elegir varias.",
  experienceOptions: {
    catas_pais: "Catas temáticas por país",
    maridajes: "Maridajes de alta gastronomía y cenas a tiempos",
    estilo_vida: "Eventos de estilo de vida / Brunch & Sparkles (fines de semana)",
    comparativas: "Catas comparativas / Máster clases sobre cepas y terruños",
    privados: "Eventos privados / Corporativos para mi grupo o empresa",
  } satisfies Record<WaitlistExperience, string>,
  schedule: "¿Qué días y horarios prefieres para asistir a nuestros encuentros?",
  scheduleOptions: {
    jueves_noche: "Jueves por la noche (after office / inicio de fin de semana)",
    viernes_noche: "Viernes por la noche",
    sabados: "Sábados (tarde / noche)",
    domingos: "Domingos (brunch / tarde)",
  } satisfies Record<WaitlistSchedule, string>,
  wineLevel: "¿Cuál es tu nivel de conocimiento o interés en el mundo del vino?",
  wineLevelOptions: {
    principiante: "Principiante / Entusiasta (quiero aprender a disfrutarlo mejor)",
    intermedio: "Intermedio (conozco cepas y me gusta descubrir nuevas etiquetas)",
    avanzado: "Avanzado / Coleccionista (busco etiquetas exclusivas y maridajes complejos)",
  } satisfies Record<WineLevel, string>,
  specialOccasion: "¿Hay alguna fecha o celebración especial próxima para la que te gustaría reservar?",
  specialOccasionPlaceholder: "Ej.: cumpleaños, aniversario, evento de empresa",
  message: "Comentario",
  messagePlaceholder: "Algo más que debamos saber (alergias, restricciones…).",
  submit: "Anotarme",
  errors: {
    fullName: "Indica tu nombre completo.",
    phone: "Indica un número de WhatsApp válido.",
    email: "Escribe un correo válido o déjalo vacío.",
    spots: "Indica cuántas personas.",
  },
  successTitle: "¡Estás en la lista!",
  successText: (name: string) =>
    `Gracias${name ? `, ${name}` : ""}. Te escribiremos por WhatsApp apenas se libere un cupo o abramos una nueva fecha.`,
  seeTastings: "Ver próximas catas",
  whatsappMessage: "Hola, me anoté en la lista de espera de El Origen.",
};

const en: typeof es = {
  eyebrow: "Waiting list & priority registration",
  titleMain: "Missed",
  titleHighlight: "out?",
  subtitle:
    "Our editions have limited spots and tend to sell out fast. By signing up you'll get early access to bookings, exclusive invitations and special perks for our upcoming tastings and food gatherings.",
  formEyebrow: "No commitment",
  formTitle: "Join the priority list",
  formSubtitle: "It only takes a minute. We'll message you on WhatsApp as soon as a spot opens up or we announce a new date.",
  sectionContact: "Contact details",
  sectionPreferences: "Preferences and habits",
  fullName: "First and last name",
  phone: "WhatsApp",
  phoneHint: "Include the area code, e.g. 0414-000-0000.",
  email: "Email",
  selectPlaceholder: "Select an option",
  spots: "How many people?",
  spotsOption: (n: number) => (n === 1 ? "1 person" : `${n} people`),
  experiences: "What kind of experiences or tastings would you like to enjoy with us?",
  experiencesHint: "You can choose several.",
  experienceOptions: {
    catas_pais: "Themed tastings by country",
    maridajes: "Fine-dining pairings and multi-course dinners",
    estilo_vida: "Lifestyle events / Brunch & Sparkles (weekends)",
    comparativas: "Comparative tastings / Master classes on grapes and terroirs",
    privados: "Private / Corporate events for my group or company",
  },
  schedule: "Which days and times do you prefer for our gatherings?",
  scheduleOptions: {
    jueves_noche: "Thursday evening (after office / start of the weekend)",
    viernes_noche: "Friday evening",
    sabados: "Saturday (afternoon / evening)",
    domingos: "Sunday (brunch / afternoon)",
  },
  wineLevel: "What is your level of knowledge or interest in wine?",
  wineLevelOptions: {
    principiante: "Beginner / Enthusiast (I want to learn to enjoy it more)",
    intermedio: "Intermediate (I know grapes and like discovering new labels)",
    avanzado: "Advanced / Collector (I look for exclusive labels and complex pairings)",
  },
  specialOccasion: "Is there a special date or celebration coming up you'd like to book for?",
  specialOccasionPlaceholder: "E.g. birthday, anniversary, company event",
  message: "Comment",
  messagePlaceholder: "Anything else we should know (allergies, restrictions…).",
  submit: "Sign me up",
  errors: {
    fullName: "Enter your full name.",
    phone: "Enter a valid WhatsApp number.",
    email: "Enter a valid email or leave it empty.",
    spots: "Tell us how many people.",
  },
  successTitle: "You're on the list!",
  successText: (name: string) =>
    `Thank you${name ? `, ${name}` : ""}. We'll message you on WhatsApp as soon as a spot opens up or we announce a new date.`,
  seeTastings: "See upcoming tastings",
  whatsappMessage: "Hi, I joined El Origen's waiting list.",
};

export const WAITLIST_COPY: Record<Language, typeof es> = { es, en };
