import type { Language } from "@/lib/i18n";
import type { OrderStatus } from "@/lib/orders";

/* Textos de "Mi cuenta" (ES/EN). */

const es = {
  loading: "Cargando tu cuenta…",
  eyebrow: "Cuenta Origen",
  greeting: (name: string) => `Hola, ${name}`,
  subtitle: "Tus reservas y entradas, en un solo lugar.",
  logout: "Cerrar sesión",
  loggingOut: "Cerrando sesión…",
  // Cupón
  couponTitle: "Tu cupón de bienvenida",
  couponText: (pct: string) => `${pct} de descuento en tu reserva. Escríbelo al reservar, usando el correo de tu cuenta.`,
  // Reservas
  bookingsTitle: "Mis reservas",
  bookingsHint: "Aquí aparecen las reservas que haces con la sesión iniciada.",
  noBookingsTitle: "Aún no tienes reservas",
  noBookingsText: "Cuando reserves una cata con tu sesión iniciada, la verás aquí con tus entradas.",
  seeTastings: "Ver próximas catas",
  status: {
    pending_payment: "Pendiente de pago",
    in_review: "Pago en revisión",
    approved: "Confirmada",
    rejected: "Pago no verificado",
    cancelled: "Anulada",
  } satisfies Record<OrderStatus, string>,
  holdExpired: "Apartado vencido",
  persons: (n: number) => `${n} ${n === 1 ? "persona" : "personas"}`,
  code: "Código",
  total: "Total",
  bookedOn: (date: string) => `Reservada el ${date}`,
  viewTickets: (n: number): string => (n === 1 ? "Ver mi entrada" : "Ver mis entradas"),
  payNow: "Pagar y reportar",
  viewOrder: "Ver reserva",
  // Datos
  profileTitle: "Mis datos",
  fullName: "Nombre completo",
  email: "Correo electrónico",
  phone: "WhatsApp",
  memberSince: "Miembro desde",
  marketing: "Novedades",
  marketingYes: "Sí, quiero recibirlas",
  marketingNo: "No",
  changeData: "¿Necesitas cambiar tus datos? Escríbenos por WhatsApp.",
  changeDataMessage: (email: string) => `Hola, quiero actualizar los datos de mi Cuenta Origen (${email}).`,
  writeUs: "Escribir por WhatsApp",
  changePassword: "Cambiar contraseña",
  error: "No pudimos cargar tu cuenta. Inténtalo de nuevo.",
  retry: "Reintentar",
};

const en: typeof es = {
  loading: "Loading your account…",
  eyebrow: "Origen Account",
  greeting: (name: string) => `Hello, ${name}`,
  subtitle: "Your bookings and tickets, in one place.",
  logout: "Sign out",
  loggingOut: "Signing out…",
  couponTitle: "Your welcome coupon",
  couponText: (pct: string) => `${pct} off your booking. Enter it at checkout using your account email.`,
  bookingsTitle: "My bookings",
  bookingsHint: "Bookings you make while signed in appear here.",
  noBookingsTitle: "No bookings yet",
  noBookingsText: "When you book a tasting while signed in, you'll see it here with your tickets.",
  seeTastings: "See upcoming tastings",
  status: {
    pending_payment: "Awaiting payment",
    in_review: "Payment under review",
    approved: "Confirmed",
    rejected: "Payment not verified",
    cancelled: "Cancelled",
  },
  holdExpired: "Hold expired",
  persons: (n: number) => `${n} ${n === 1 ? "person" : "people"}`,
  code: "Code",
  total: "Total",
  bookedOn: (date: string) => `Booked on ${date}`,
  viewTickets: (n: number) => (n === 1 ? "View my ticket" : "View my tickets"),
  payNow: "Pay and report",
  viewOrder: "View booking",
  profileTitle: "My details",
  fullName: "Full name",
  email: "Email",
  phone: "WhatsApp",
  memberSince: "Member since",
  marketing: "News",
  marketingYes: "Yes, I want to receive them",
  marketingNo: "No",
  changeData: "Need to change your details? Message us on WhatsApp.",
  changeDataMessage: (email: string) => `Hello, I'd like to update the details of my Origen Account (${email}).`,
  writeUs: "Message us on WhatsApp",
  changePassword: "Change password",
  error: "We couldn't load your account. Please try again.",
  retry: "Try again",
};

export const ACCOUNT_COPY: Record<Language, typeof es> = { es, en };
