import type { Language } from "@/lib/i18n";

/* Textos del registro (ES/EN). Los rótulos del formulario y el botón son literales del cliente. */

const es = {
  eyebrow: "Cuenta Origen",
  title: "Crea tu Cuenta Origen",
  subtitle: "Un registro sencillo para reservar más rápido y tener tus entradas siempre a mano.",
  benefits: [
    "Reserva más rápido: tus datos quedan guardados.",
    "Consulta tus reservas y entradas en un solo lugar.",
    "Entérate primero de las próximas catas.",
  ],
  fullName: "Nombre completo",
  email: "Correo electrónico",
  phone: "WhatsApp",
  phoneHint: "Con código de área, p. ej. 0414-000-0000.",
  password: "Contraseña",
  passwordHint: "Mínimo 8 caracteres.",
  /** "Soy mayor de 18 años y acepto los Términos y Condiciones." (texto completo en policies.ts) */
  termsLinkText: "Términos y Condiciones",
  termsLinkAria: "Términos y Condiciones (se abre en una pestaña nueva)",
  marketing: "Quiero recibir novedades y próximas catas por correo o WhatsApp (opcional).",
  submit: "Crear mi Cuenta Origen",
  submitting: "Creando tu cuenta…",
  haveAccount: "¿Ya tienes cuenta?",
  login: "Ingresar",
  errors: {
    summary: "Revisa los campos marcados.",
    fullName: "Indica tu nombre completo.",
    email: "Escribe un correo válido.",
    phone: "Indica un número de WhatsApp válido.",
    password: "La contraseña debe tener al menos 8 caracteres.",
    terms: "Debes confirmar que eres mayor de 18 años y aceptar los Términos y Condiciones.",
    emailTaken: "Ya existe una cuenta con ese correo.",
    emailTakenAction: "Ingresa con tu contraseña",
    rateLimited: "Demasiados intentos. Espera unos minutos e inténtalo de nuevo.",
    generic: "No pudimos crear la cuenta. Revisa tus datos e inténtalo de nuevo.",
    network: "Error de conexión. Inténtalo de nuevo.",
  },
  // Bienvenida
  welcomeEyebrow: "Cuenta creada",
  welcomeTitle: (name: string) => `Te damos la bienvenida, ${name}`,
  welcomeText: "Tu Cuenta Origen está lista. Cuando reserves con la sesión iniciada, tus entradas aparecerán en Mi cuenta.",
  couponTitle: "Tu cupón de bienvenida",
  couponText: (pct: string) => `${pct} de descuento en tu reserva. Escríbelo al reservar, usando el correo de tu cuenta.`,
  continue: "Continuar con mi reserva",
  seeTastings: "Ver próximas catas",
  goAccount: "Ir a mi cuenta",
};

const en: typeof es = {
  eyebrow: "Origen Account",
  title: "Create your Origen Account",
  subtitle: "A quick sign-up to book faster and keep your tickets at hand.",
  benefits: [
    "Book faster: your details are saved.",
    "See your bookings and tickets in one place.",
    "Be the first to hear about upcoming tastings.",
  ],
  fullName: "Full name",
  email: "Email",
  phone: "WhatsApp",
  phoneHint: "Include the area code, e.g. 0414-000-0000.",
  password: "Password",
  passwordHint: "At least 8 characters.",
  termsLinkText: "Terms and Conditions",
  termsLinkAria: "Terms and Conditions (opens in a new tab)",
  marketing: "I'd like to receive news and upcoming tastings by email or WhatsApp (optional).",
  submit: "Create my Origen Account",
  submitting: "Creating your account…",
  haveAccount: "Already have an account?",
  login: "Sign in",
  errors: {
    summary: "Please check the highlighted fields.",
    fullName: "Enter your full name.",
    email: "Enter a valid email address.",
    phone: "Enter a valid WhatsApp number.",
    password: "Your password must be at least 8 characters long.",
    terms: "You must confirm you are over 18 and accept the Terms and Conditions.",
    emailTaken: "An account with this email already exists.",
    emailTakenAction: "Sign in with your password",
    rateLimited: "Too many attempts. Please wait a few minutes and try again.",
    generic: "We couldn't create your account. Check your details and try again.",
    network: "Connection error. Please try again.",
  },
  welcomeEyebrow: "Account created",
  welcomeTitle: (name: string) => `Welcome to El Origen, ${name}`,
  welcomeText: "Your Origen Account is ready. When you book while signed in, your tickets will appear in My account.",
  couponTitle: "Your welcome coupon",
  couponText: (pct: string) => `${pct} off your booking. Enter it at checkout using your account email.`,
  continue: "Continue with my booking",
  seeTastings: "See upcoming tastings",
  goAccount: "Go to my account",
};

export const REGISTER_COPY: Record<Language, typeof es> = { es, en };
